workflow:
  name: CI

image:
  name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/maven:3.9.9-eclipse-temurin-21-alpine

stages:
  - build
  - test
  - grade

maven-compile:
  stage: build
  artifacts:
    when: always
    paths:
      - target
  script:
    - mvn -V --color always -ntp -fae test-compile -Pci -Dasciidoctor.skip

maven-verify:
  stage: test
  needs:
    - maven-compile
  artifacts:
    when: always
    paths:
      - target
      - maven.log
  script:
    - mvn -V --color always -ntp -fae verify -Pci -Dasciidoctor.skip | tee maven.log

autograding:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/uhafner/autograding-gitlab-action:v3.1.0
  stage: grade
  needs:
    - maven-verify
  when: always
  script:
    - java -cp @/app/jib-classpath-file edu.hm.hafner.grading.gitlab.GitLabAutoGradingRunner
  variables:
    MAX_WARNING_COMMENTS: 10
    MAX_COVERAGE_COMMENTS: 10
    CONFIG: |
      {
        "tests": [
          {
            "name": "Modultests",
            "tools": [
              {
                "id": "junit",
                "name": "Modultests",
                "pattern": "**/target/*-reports/TEST-edu.hm.hafner.java2.assignment*.xml"
              }
            ],
            "failureRateImpact": -1,
            "maxScore": 100
          },
          {
            "name": "Verletzung der Architekturrichtlinien",
            "tools": [
              {
                "id": "junit",
                "icon": "no_entry_sign",
                "name": "Architekturrichtlinien",
                "pattern": "**/target/surefire-reports/TEST-edu.hm.hafner.java2.ArchitectureTest.xml"
              }
            ],
            "failureRateImpact": -1,
            "maxScore": 100
          }
        ],
        "analysis": [
          {
            "name": "Verletzungen der Richtlinien",
            "id": "style",
            "tools": [
              {
                "id": "checkstyle",
                "pattern": "**/target/checkstyle-*/checkstyle-result.xml"
              },
              {
                "id": "pmd",
                "pattern": "**/target/pmd-*/pmd.xml"
              }
            ],
            "errorImpact": -1,
            "highImpact": -1,
            "normalImpact": -1,
            "lowImpact": -1,
            "maxScore": 100
          },
          {
            "name": "Potentielle Fehler",
            "id": "bugs",
            "icon": "bug",
            "tools": [
              {
                "id": "spotbugs",
                "sourcePath": "src/main/java",
                "pattern": "**/target/**spotbugsXml.xml"
              },
              {
                "id": "error-prone",
                "pattern": "**/maven.log"
              }
            ],
            "errorImpact": -3,
            "highImpact": -3,
            "normalImpact": -3,
            "lowImpact": -3,
            "maxScore": 100
          }
        ],
        "coverage": [
          {
            "name": "Testüberdeckung",
            "tools": [
              {
                "id": "jacoco",
                "metric": "line",
                "name": "Zeilenüberdeckung",
                "sourcePath": "src/main/java",
                "pattern": "**/target/site/jacoco/jacoco.xml"
              },
              {
                "id": "jacoco",
                "metric": "branch",
                "name": "Zweigüberdeckung",
                "sourcePath": "src/main/java",
                "pattern": "**/target/site/jacoco/jacoco.xml"
              }
            ],
            "maxScore": 100,
            "missedPercentageImpact": -1
          }
        ]
      }
