name: 'Autograding'

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:

    runs-on: [ubuntu-latest]
    name: Build, test and autograde on Ubuntu

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
      - name: Build with Maven
        run: mvn -V --color always -ntp clean verify -Pci | tee maven.log
      - name: Extract pull request number
        uses: jwalton/gh-find-current-pr@v1
        id: pr
      - name: Run Quality Monitor
        uses: uhafner/autograding-github-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.number }}
          config: >
            {
              "tests": [
                {
                  "name": "Modultests",
                  "tools": [
                    {
                      "id": "junit",
                      "name": "Modultests",
                      "pattern": "**/target/*-reports/TEST-edu.hm.hafner.java2.assignment*.xml"
                    }
                  ],
                  "failureRateImpact": -1,
                  "maxScore": 100
                },
                {
                  "name": "Verletzung der Architekturrichtlinien",
                  "icon": "no_entry_sign",
                  "tools": [
                    {
                      "id": "junit",
                      "icon": "no_entry_sign",
                      "name": "Architekturrichtlinien",
                      "pattern": "**/target/surefire-reports/TEST-edu.hm.hafner.java2.ArchitectureTest.xml"
                    }
                  ],
                  "failureRateImpact": -1,
                  "maxScore": 100
                }
              ],
              "analysis": [
                {
                  "name": "Verletzungen der Richtlinien",
                  "id": "style",
                  "tools": [
                    {
                      "id": "checkstyle",
                      "pattern": "**/target/checkstyle-*/checkstyle-result.xml"
                    },
                    {
                      "id": "pmd",
                      "pattern": "**/target/pmd-*/pmd.xml"
                    }
                  ],
                  "errorImpact": -1,
                  "highImpact": -1,
                  "normalImpact": -1,
                  "lowImpact": -1,
                  "maxScore": 100
                },
                {
                  "name": "Potentielle Fehler",
                  "id": "bugs",
                  "icon": "bug",
                  "tools": [
                    {
                      "id": "spotbugs",
                      "sourcePath": "src/main/java",
                      "pattern": "**/target/**spotbugsXml.xml"
                    },
                    {
                      "id": "error-prone",
                      "pattern": "**/maven.log"
                    }
                  ],
                  "errorImpact": -5,
                  "highImpact": -5,
                  "normalImpact": -5,
                  "lowImpact": -5,
                  "maxScore": 100
                }
              ],
              "coverage": [
                {
                  "name": "Testüberdeckung",
                  "tools": [
                    {
                      "id": "jacoco",
                      "metric": "line",
                      "name": "Zeilenüberdeckung",
                      "sourcePath": "src/main/java",
                      "pattern": "**/target/site/jacoco/jacoco.xml"
                    },
                    {
                      "id": "jacoco",
                      "metric": "branch",
                      "name": "Zweigüberdeckung",
                      "sourcePath": "src/main/java",
                      "pattern": "**/target/site/jacoco/jacoco.xml"
                    }
                  ],
                  "maxScore": 100,
                  "missedPercentageImpact": -1
                }
              ]
            }
